# Data
train_json: datasets/coco/train.json
val_json: datasets/coco/val.json
class_names: [person, bicycle, car, motorcycle, airplane, bus, train, truck, boat, traffic_light,
              fire_hydrant, stop_sign, parking_meter, bench, bird, cat, dog, horse, sheep, cow,
              elephant, bear, zebra, giraffe, backpack, umbrella, handbag, tie, suitcase, frisbee,
              skis, snowboard, sports_ball, kite, baseball_bat, baseball_glove, skateboard,
              surfboard, tennis_racket, bottle, wine_glass, cup, fork, knife, spoon, bowl, banana,
              apple, sandwich, orange, broccoli, carrot, hot_dog, pizza, donut, cake, chair, couch,
              potted_plant, bed, dining_table, toilet, tv, laptop, mouse, remote, keyboard,
              cell_phone, microwave, oven, toaster, sink, refrigerator, book, clock, vase, scissors,
              teddy_bear, hair_drier, toothbrush]
recall_steps: 101 #valore predifinito
image_mean: [123., 117., 104.]
image_stddev: [1., 1, 1.]

# Model
model: SSD
backbone:
  name: VGG16
  num_stages: 6
input_size: 300
anchor_scales: [0.07, 0.15, 0.3375, 0.525, 0.7125, 0.9]
anchor_aspect_ratios: [[1, 2], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2], [1, 2]]

# Training
training_configs: 
  batch_size: 
    - 8 
    - 16
    - 32 #32
  optim:
    name: SGD
    lr: 
      - 0.001
      - 0.1
      - 0.5
    momentum: 
      - 0.0
      - 0.5
      - 0.8
    weight_decay: 
      - 0.0001
      - 0.0005
      - 0.001
  scheduler:
    name: MultiStepLR
    milestones: [90, 110]
    gamma: 0.1
  early_stopping:
    patience: 
      - 10
    min_delta: 
     - 0.01

training_config_2: 
  batch_size: 
    - 8 
    - 16
    - 32 #32
  optim:
    name: SGD
    lr: 
      - [0.0005,0.001, 0.002]
      - [0.05, 0.1, 0.2]
      - [0.25, 0.5, 0.75]
    momentum: 
      - [0.0, 0.05, 0.1]
      - [0.3, 0.5, 0.7]
      - [0.6, 0.8, 0.9]
    weight_decay: 
      - [0.00005, 0.0001, 0.0002]
      - [0.0003, 0.0005, 0.0008]
      - [0.0009 ,0.001, 0.004]
  scheduler:
    name: MultiStepLR
    milestones: [90, 110]
    gamma: 0.1
  early_stopping:
    patience: 
      - 10
    min_delta: 
     - 0.01